# These defaults are actually for arise (loam) working with mid360
eskf_node:
  ros__parameters:
    verbose_diagnostics: true
    verbose_diagnostics_hz: 0.25
    accelerometer_unit_is_g: true
    pose_format_is_odometry: false
    orientation_meas_stddev_deg: 5.0
    imu_topic: /livox/imu/
    meas_topic: /laser_odometry
